# CLEAN
clean:
  tags: [android]
  stage: clean
  only:
    - tags
  script:
    - ./gradlew clean

# TESTS
sdk:test:release:
  tags: [android]
  stage: test
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - ./gradlew sdk:testReleaseUnitTest
  artifacts:
    reports:
      junit: sdk/build/test-results/testReleaseUnitTest/TEST-*.xml

# DOCUMENTATION
sdk:documentation:release:
  tags: [android]
  stage: documentation
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - ./gradlew sdk:generateDocumentation
  artifacts:
    paths:
      - sdk/build/libs/

# SOURCES
sdk:sources:release:
  tags: [android]
  stage: sources
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - ./gradlew sdk:sourcesJar
  artifacts:
    paths:
      - sdk/build/libs/


# BUILD
sdk:build:release:
  tags: [android]
  stage: build
  only:
    - /^\d+\.\d+\.\d+$/
  script:
    - ./gradlew sdk:assembleRelease
  artifacts:
    paths:
      - sdk/build/outputs/aar/
    expire_in: 1 day

# DEPLOY
sdk:deploy:release:
  tags: [android]
  stage: deploy
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - ./gradlew sdk:publishReleasePublicationToStagingRepository
